# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yuanxiaolong.github.io
title: Sam小龙
subtitle: 喵喵~
author: xiaolong.yuanxl
simple_search: http://www.baidu.com?wd=
description: blog

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email: 232351936@qq.com

background: bg.jpg
avatar: avatar.png
# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /blog/:year/:month/:day/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
markdown: kramdown #rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart
highlighter: pygments # default python pygments have been replaced by pygments.rb

paginate: 4          # Posts per page on the blog index
# paginate_path:  "posts"    #"posts/:num"  # Directory base for pagination URLs eg. /posts/2/
# pagination_dir: "posts"
paginate_path: "pages/page:num"
recent_posts: 1       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: "<!--more-->"

# pages: "./_pages"

titlecase: true       # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [asides/recent_posts.html, asides/github.html, asides/delicious.html, asides/pinboard.html, asides/googleplus.html]

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:
# post_asides:
# page_asides:

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: yuanxiaolong
#github_repo_count: 0
#github_show_profile_link: true
#github_skip_forks: true

# Twitter
#twitter_user:
#twitter_tweet_button: true

# Google +1
#google_plus_one: false
#google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
#googleplus_user:
#googleplus_hidden: false

# Pinboard
#pinboard_user:
#pinboard_count: 3

# Delicious
#delicious_user:
#delicious_count: 3

# Disqus Comments
#disqus_short_name:
#disqus_show_comment_count: false

# Google Analytics
#google_analytics_tracking_id:

# Facebook Like
#facebook_like: false
